# secrets:
#   fernet_key:
#     file: ./fernet.key
#   auth_secret:
#       file: ./auth.key
    # external: true USE IN PROD WITH SWARM and `docker secret create auth_secret fernet.key`

services:
  init-secrets:
    build:
      context: .
      dockerfile: scripts/Dockerfile
    volumes:
      - ./scripts:/scripts
      - secrets-store:/secrets
  
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: certsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # command: >
    #   postgres
    #   -c log_statement=none
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    # volumes são montados para facilitar o desenvolvimento, mas em produção o código deve ser copiado para a imagem
    volumes:
      - ./api:/app/api
      - ./shared/shared:/app/shared
      - secrets-store:/secrets
    environment:
      POSTGRES_DB: certsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      # AUTH_SECRET_FILE: "/run/secrets/auth_secret"
    ports:
      - "8080:8080"
    # secrets:
    #   - fernet_key
    #   - auth_secret
    depends_on:
      init-secrets: 
        condition: service_completed_successfully
      migrations:
        condition: service_completed_successfully
      # - rabbitmq:
      #     condition: service_healthy

  migrations:
    build:
      context: .
      dockerfile: alembic/Dockerfile
    volumes:
      - ./alembic:/app/alembic
      - ./shared/shared:/app/shared
    environment:
      POSTGRES_DB: certsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    depends_on:
      postgres:
        condition: service_healthy

  ui:
    build: ./ui
    ports:
      - "3000:3000"
    # remove on Production, copy files to image instead
    volumes:
      - ./ui:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - api

  # worker:
  #   build: 
  #     context: .
  #     dockerfile: worker/Dockerfile
  #   # volumes são montados para facilitar o desenvolvimento, mas em produção o código deve ser copiado para a imagem
  #   volumes:
  #     - ./worker:/app/worker
  #     - ./shared/shared:/app/shared
  #   environment:
  #     POSTGRES_DB: certsdb
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_HOST: postgres
  #   depends_on:
  #     - rabbitmq
  #     - postgres

# persistent thru restart
volumes:
  postgres_data:
  secrets-store: