version: "3.9"

secrets:
  aes_key:
    file: ./aes_key.key

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: certsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: >
      postgres
      -c log_statement=mod
      -c log_parameter_max_length=128
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: 
      context: .
      dockerfile: api/Dockerfile
    # volumes são montados para facilitar o desenvolvimento, mas em produção o código deve ser copiado para a imagem
    volumes:
      - ./api:/app/api
      - ./shared/shared:/app/shared
    environment:
      POSTGRES_DB: certsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      # AES_SECRET_KEY: "${AES_SECRET_KEY}"
    ports:
      - "8080:8080"
    secrets:
      - aes_key
    depends_on:
      - postgres
      - rabbitmq

  ui-components:
    build: ./pages
    ports:
      - "3000:3000"
    # remove on Production, copy files to image instead
    volumes:
      - ./pages:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python main.py --reload
    depends_on:
      - api

  worker:
    build: 
      context: .
      dockerfile: worker/Dockerfile
    # volumes são montados para facilitar o desenvolvimento, mas em produção o código deve ser copiado para a imagem
    volumes:
      - ./worker:/app/worker
      - ./shared/shared:/app/shared
    environment:
      POSTGRES_DB: certsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      AES_SECRET_KEY: "${AES_SECRET_KEY}"
    depends_on:
      - rabbitmq
      - postgres